# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cfy/programs/C/crypt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cfy/programs/C/crypt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cfy/programs/C/crypt/CMakeFiles /home/cfy/programs/C/crypt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cfy/programs/C/crypt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cryptoc

# Build rule for target.
cryptoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptoc
.PHONY : cryptoc

# fast build rule for target.
cryptoc/fast:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/build
.PHONY : cryptoc/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

aes.o: aes.c.o

.PHONY : aes.o

# target to build an object file
aes.c.o:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/aes.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/aes.c.o
.PHONY : aes.c.o

aes.i: aes.c.i

.PHONY : aes.i

# target to preprocess a source file
aes.c.i:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/aes.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/aes.c.i
.PHONY : aes.c.i

aes.s: aes.c.s

.PHONY : aes.s

# target to generate assembly for a file
aes.c.s:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/aes.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/aes.c.s
.PHONY : aes.c.s

cryptoc.o: cryptoc.c.o

.PHONY : cryptoc.o

# target to build an object file
cryptoc.c.o:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/cryptoc.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cryptoc.c.o
.PHONY : cryptoc.c.o

cryptoc.i: cryptoc.c.i

.PHONY : cryptoc.i

# target to preprocess a source file
cryptoc.c.i:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/cryptoc.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cryptoc.c.i
.PHONY : cryptoc.c.i

cryptoc.s: cryptoc.c.s

.PHONY : cryptoc.s

# target to generate assembly for a file
cryptoc.c.s:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/cryptoc.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cryptoc.c.s
.PHONY : cryptoc.c.s

des.o: des.c.o

.PHONY : des.o

# target to build an object file
des.c.o:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/des.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/des.c.o
.PHONY : des.c.o

des.i: des.c.i

.PHONY : des.i

# target to preprocess a source file
des.c.i:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/des.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/des.c.i
.PHONY : des.c.i

des.s: des.c.s

.PHONY : des.s

# target to generate assembly for a file
des.c.s:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/des.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/des.c.s
.PHONY : des.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/main.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/main.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/main.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

sha256.o: sha256.c.o

.PHONY : sha256.o

# target to build an object file
sha256.c.o:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/sha256.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sha256.c.o
.PHONY : sha256.c.o

sha256.i: sha256.c.i

.PHONY : sha256.i

# target to preprocess a source file
sha256.c.i:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/sha256.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sha256.c.i
.PHONY : sha256.c.i

sha256.s: sha256.c.s

.PHONY : sha256.s

# target to generate assembly for a file
sha256.c.s:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/sha256.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sha256.c.s
.PHONY : sha256.c.s

sm4.o: sm4.c.o

.PHONY : sm4.o

# target to build an object file
sm4.c.o:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/sm4.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sm4.c.o
.PHONY : sm4.c.o

sm4.i: sm4.c.i

.PHONY : sm4.i

# target to preprocess a source file
sm4.c.i:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/sm4.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sm4.c.i
.PHONY : sm4.c.i

sm4.s: sm4.c.s

.PHONY : sm4.s

# target to generate assembly for a file
sm4.c.s:
	$(MAKE) -f CMakeFiles/cryptoc.dir/build.make CMakeFiles/cryptoc.dir/sm4.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sm4.c.s
.PHONY : sm4.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... cryptoc"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... aes.o"
	@echo "... aes.i"
	@echo "... aes.s"
	@echo "... cryptoc.o"
	@echo "... cryptoc.i"
	@echo "... cryptoc.s"
	@echo "... des.o"
	@echo "... des.i"
	@echo "... des.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sha256.o"
	@echo "... sha256.i"
	@echo "... sha256.s"
	@echo "... sm4.o"
	@echo "... sm4.i"
	@echo "... sm4.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

